# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Verify

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
#      - name: Ensure SHA pinned actions
#        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@8877889a5717dad0b139f1d2925689aa68f88a43

      - uses: subosito/flutter-action@v2
#      - name: Ensure SHA pinned actions
#        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@8877889a5717dad0b139f1d2925689aa68f88a43
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter --version

      - name: Run flutter publish (dry run)
        run: flutter pub publish --dry-run